GET http://localhost:3000/invitations/all

###
GET http://localhost:3000/invitations/get/6054c96a08105817ee045bee

###
POST http://localhost:3000/invitations/create
Content-Type: application/json

{
    "name": "Purry",
    "party": "Baby Shower",
    "date": "1 April 2021",
    "hour": "11.00 PM",
    "address": "Sukarno Hatta 21"
}

###
PATCH http://localhost:3000/invitations/update/6054c96a08105817ee045bee
Content-Type: application/json

{
    "name": "Cherry",
    "party": "Wedding",
    "date": "31 February 2021",
    "hour": "03.00 PM",
    "address": "Tokyo"
}

###
DELETE http://localhost:3000/invitations/delete/6054c96a08105817ee045bee